# base surrealdb image
FROM ubuntu:latest

# install latest updates
RUN apt update && apt upgrade -y

# install dependencies
RUN apt install curl -y
RUN curl -sSf https://install.surrealdb.com | sh

# launch db
CMD surreal start --user root --pass root file:///data/db