# base linux image
FROM ubuntu:latest

# install latest updates
RUN apt update && apt upgrade -y

# install dependencies
RUN apt install cargo -y
RUN apt install pkg-config -y
RUN apt install libssl-dev -y

# copy server code and precompiled client code
COPY /server /server

# copy env file
COPY .env /server/.env

# set working dir
WORKDIR /server

# launch server
CMD cargo run --release